#!/bin/bash

echo "ALX School"

echo "ALX School is so cool!"
 master

echo "ALX School is so cool!"


echo "ALX School is so cool!"
 master

update_script
echo "ALX School"

echo "ALX School is so cool!"
master

update_script

